//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mentee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mentee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Home.Mentee", typeof(Mentee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose signing option.
        /// </summary>
        public static string ChoseSigningOption {
            get {
                return ResourceManager.GetString("ChoseSigningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        public static string DocumentStatus {
            get {
                return ResourceManager.GetString("DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is on sick leave.
        /// </summary>
        public static string IsOnSickLeave {
            get {
                return ResourceManager.GetString("IsOnSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor(s).
        /// </summary>
        public static string Mentor_s_ {
            get {
                return ResourceManager.GetString("Mentor(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentorship total hours.
        /// </summary>
        public static string MentorshipTotalHours {
            get {
                return ResourceManager.GetString("MentorshipTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentorship until/from.
        /// </summary>
        public static string MentorshipUntil_from {
            get {
                return ResourceManager.GetString("MentorshipUntil/from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no documents found.
        /// </summary>
        public static string NoDocumentsFound {
            get {
                return ResourceManager.GetString("NoDocumentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of signing.
        /// </summary>
        public static string TimeOfSigning {
            get {
                return ResourceManager.GetString("TimeOfSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way of Signing.
        /// </summary>
        public static string WayOfSigning {
            get {
                return ResourceManager.GetString("WayOfSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current internship.
        /// </summary>
        public static string YourCurrentInternship {
            get {
                return ResourceManager.GetString("YourCurrentInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current mentorship.
        /// </summary>
        public static string YourCurrentMentorship {
            get {
                return ResourceManager.GetString("YourCurrentMentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Documents.
        /// </summary>
        public static string YourDocuments {
            get {
                return ResourceManager.GetString("YourDocuments", resourceCulture);
            }
        }
    }
}
