//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Add {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mentee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mentee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Add.Mentee", typeof(Mentee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (currently active).
        /// </summary>
        public static string _currently_active_ {
            get {
                return ResourceManager.GetString("(currently active)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp; Create User.
        /// </summary>
        public static string AddCreateUser {
            get {
                return ResourceManager.GetString("AddCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mentee.
        /// </summary>
        public static string AddMentee {
            get {
                return ResourceManager.GetString("AddMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Mentor.
        /// </summary>
        public static string AssignMentor {
            get {
                return ResourceManager.GetString("AssignMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee/Intern.
        /// </summary>
        public static string EmployeeIntern {
            get {
                return ResourceManager.GetString("EmployeeIntern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Mentees.
        /// </summary>
        public static string EmployeeMentees {
            get {
                return ResourceManager.GetString("EmployeeMentees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory supervisor.
        /// </summary>
        public static string FactorySupervisor {
            get {
                return ResourceManager.GetString("FactorySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-time.
        /// </summary>
        public static string Full_time {
            get {
                return ResourceManager.GetString("Full-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Document.
        /// </summary>
        public static string GenerateDocument {
            get {
                return ResourceManager.GetString("GenerateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id code.
        /// </summary>
        public static string IdCode {
            get {
                return ResourceManager.GetString("IdCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern Mentees.
        /// </summary>
        public static string InternMentees {
            get {
                return ResourceManager.GetString("InternMentees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern supervisor.
        /// </summary>
        public static string InternSupervisor {
            get {
                return ResourceManager.GetString("InternSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee&apos;s mentor.
        /// </summary>
        public static string Mentee_sMentor {
            get {
                return ResourceManager.GetString("Mentee\'sMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee&apos;s name.
        /// </summary>
        public static string Mentee_sName {
            get {
                return ResourceManager.GetString("Mentee\'sName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee&apos;s type.
        /// </summary>
        public static string Mentee_sType {
            get {
                return ResourceManager.GetString("Mentee\'sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee from date.
        /// </summary>
        public static string MenteeFromDate {
            get {
                return ResourceManager.GetString("MenteeFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee Info.
        /// </summary>
        public static string MenteeInfo {
            get {
                return ResourceManager.GetString("MenteeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee for total hours.
        /// </summary>
        public static string MenteeTotaHours {
            get {
                return ResourceManager.GetString("MenteeTotaHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee type.
        /// </summary>
        public static string MenteeType {
            get {
                return ResourceManager.GetString("MenteeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee until date.
        /// </summary>
        public static string MenteeUntilDate {
            get {
                return ResourceManager.GetString("MenteeUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentors.
        /// </summary>
        public static string Mentors {
            get {
                return ResourceManager.GetString("Mentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentorship until/from/total hours.
        /// </summary>
        public static string MentorshipUntil_from {
            get {
                return ResourceManager.GetString("MentorshipUntil/from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor for total hours.
        /// </summary>
        public static string MentorTotalHours {
            get {
                return ResourceManager.GetString("MentorTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee added, user created and email-notification sent..
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string OptionEmployee {
            get {
                return ResourceManager.GetString("OptionEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern.
        /// </summary>
        public static string OptionIntern {
            get {
                return ResourceManager.GetString("OptionIntern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocational school (gep).
        /// </summary>
        public static string OptionVocationalSchool {
            get {
                return ResourceManager.GetString("OptionVocationalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probation.
        /// </summary>
        public static string Probation {
            get {
                return ResourceManager.GetString("Probation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Program.
        /// </summary>
        public static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töötukassa.
        /// </summary>
        public static string Töötukassa {
            get {
                return ResourceManager.GetString("Töötukassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
