//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Details {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeMentee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeMentee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Details.EmployeeMentee", typeof(EmployeeMentee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sick leave.
        /// </summary>
        public static string AddSickLeave {
            get {
                return ResourceManager.GetString("AddSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Mentor.
        /// </summary>
        public static string AssignedMentor {
            get {
                return ResourceManager.GetString("AssignedMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee details.
        /// </summary>
        public static string MenteeDetails {
            get {
                return ResourceManager.GetString("MenteeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee Info.
        /// </summary>
        public static string MenteeInfo {
            get {
                return ResourceManager.GetString("MenteeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor.
        /// </summary>
        public static string Mentor {
            get {
                return ResourceManager.GetString("Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor from date.
        /// </summary>
        public static string MentorFromDate {
            get {
                return ResourceManager.GetString("MentorFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor until date.
        /// </summary>
        public static string MentorUntilDate {
            get {
                return ResourceManager.GetString("MentorUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mentor.
        /// </summary>
        public static string NewMentor {
            get {
                return ResourceManager.GetString("NewMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mentor from date.
        /// </summary>
        public static string NewMentorFromDate {
            get {
                return ResourceManager.GetString("NewMentorFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mentor for total hours.
        /// </summary>
        public static string NewMentorTotalHours {
            get {
                return ResourceManager.GetString("NewMentorTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mentor until date.
        /// </summary>
        public static string NewMentorUntilDate {
            get {
                return ResourceManager.GetString("NewMentorUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason of change for another mentor.
        /// </summary>
        public static string ReasonOfChange {
            get {
                return ResourceManager.GetString("ReasonOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick leave from date.
        /// </summary>
        public static string SickLeaveFromDate {
            get {
                return ResourceManager.GetString("SickLeaveFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick leave info.
        /// </summary>
        public static string SickLeaveInfo {
            get {
                return ResourceManager.GetString("SickLeaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick leave reason.
        /// </summary>
        public static string SickLeaveReason {
            get {
                return ResourceManager.GetString("SickLeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick leave until date.
        /// </summary>
        public static string SickLeaveUntilDate {
            get {
                return ResourceManager.GetString("SickLeaveUntilDate", resourceCulture);
            }
        }
    }
}
