//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.View.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.View.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document Sample.
        /// </summary>
        public static string AddDocumentSample {
            get {
                return ResourceManager.GetString("AddDocumentSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mentee.
        /// </summary>
        public static string AddMentee {
            get {
                return ResourceManager.GetString("AddMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mentor.
        /// </summary>
        public static string AddMentor {
            get {
                return ResourceManager.GetString("AddMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supervisor.
        /// </summary>
        public static string AddSupervisor {
            get {
                return ResourceManager.GetString("AddSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Samples.
        /// </summary>
        public static string Document_Samples {
            get {
                return ResourceManager.GetString("Document Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Error.
        /// </summary>
        public static string IdentityError {
            get {
                return ResourceManager.GetString("IdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee.
        /// </summary>
        public static string Mentee {
            get {
                return ResourceManager.GetString("Mentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee-Employees.
        /// </summary>
        public static string Mentee_Employees {
            get {
                return ResourceManager.GetString("Mentee-Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee-Interns.
        /// </summary>
        public static string Mentee_Interns {
            get {
                return ResourceManager.GetString("Mentee-Interns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentors.
        /// </summary>
        public static string Mentors {
            get {
                return ResourceManager.GetString("Mentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueIsInvalidAccessor.
        /// </summary>
        public static string ValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ValueIsInvalidAccessor", resourceCulture);
            }
        }
    }
}
